# Generated by Django 3.0.3 on 2020-03-06 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_squashed_0006_auto_20200306_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='design_details',
            field=models.ManyToManyField(limit_choices_to={'category__name': None}, to='products.CategoryDesignDetail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(limit_choices_to={'category__name': None}, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.CategoryType'),
        ),
    ]
