# Generated by Django 3.0.3 on 2020-03-07 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200306_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='design_details',
            field=models.ManyToManyField(to='products.CategoryDesignDetail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(to='products.CategoryMaterial'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.CategoryType'),
        ),
    ]
