# Generated by Django 3.0.4 on 2020-04-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_productgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='design_details',
            field=models.ManyToManyField(blank=True, to='products.CategoryDesignDetail'),
        ),
    ]
