# Generated by Django 3.0.8 on 2020-07-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_vector',
            field=models.BinaryField(blank=True),
        ),
    ]
