# Generated by Django 3.0.8 on 2020-07-27 15:31

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_image_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_vector',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False),
        ),
    ]
