# Generated by Django 3.0.3 on 2020-02-11 16:50

from django.db import migrations
import pandas as pd

categories = ('bags', 'wallets')
colors = (
    'Black',
    'Blue',
    'Brown',
    'Green',
    'Grey',
    'Multicolor',
    'Neutral',
    'Orange',
    'Pink',
    'Purple',
    'Red',
    'White',
    'Yellow'
)
design_details = (
    'Bow',
    'Buckle',
    'Clasp',
    'Crossbody Strap',
    'Drawstring',
    'Knot',
    'Lock',
    'Metal',
    'Metal Chain',
    'Studs',
    'Top Handle',
    'Woven',
    'Zipper'
)
materials = (
    'Cordura',
    'Cotton Canvas',
    'Croc',
    'Denim',
    'Embossed-croc',
    'Embossed-python',
    'Haircalf',
    'Knit',
    'Leather',
    'Mesh',
    'Metal',
    'Neoprene',
    'Nylon',
    'Plastic',
    'Python',
    'Straw',
    'Vacchetta',
    'Vegan',
    'Vegetable-tanned leather'
)
types = (
    'Backpack',
    'Baguette',
    'Belt',
    'Bifold',
    'Briefcase',
    'Bucket',
    'Camera',
    'Card Case',
    'Clutch',
    'Crossbody',
    'Doctor’s',
    'Duffle',
    'Envelope',
    'Fanny Pack',
    'Garment',
    'Gym',
    'Hobo',
    'ID Card',
    'Laptop',
    'Large',
    'Messenger',
    'Money Clip',
    'Passport Holder',
    'Portfolio',
    'Pouch',
    'Saddle',
    'Satchel',
    'Slingback',
    'Totes',
    'Travel',
    'Trifold',
    'Zippered'
)
attributes = (colors, design_details, materials, types)
models = ('Color', 'DesignDetail', 'Material', 'Type')


def populate_category(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Category.objects.bulk_create([Category(name=category) for category in categories])


def populate_attributes(apps, schema_editor):
    for attribute, model in zip(attributes, models):
        Model = apps.get_model('products', model)
        Model.objects.bulk_create([Model(name=name) for name in attribute])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(populate_category),
        migrations.RunPython(populate_attributes)
    ]
