# Generated by Django 3.0.2 on 2020-01-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydesigndetail',
            old_name='name',
            new_name='design_detail',
        ),
        migrations.RenameField(
            model_name='categorytype',
            old_name='name',
            new_name='type',
        ),
    ]
