# Generated by Django 3.0.3 on 2020-02-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200229_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='design_details',
            field=models.ManyToManyField(to='products.CategoryDesignDetail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(to='products.CategoryMaterial'),
        ),
    ]
