# Generated by Django 3.0.4 on 2020-03-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200307_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductGroup',
        ),
    ]
