# Generated by Django 3.0.2 on 2020-01-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_types',
            field=models.ManyToManyField(to='products.CategoryType'),
        ),
    ]
