# Generated by Django 3.0.5 on 2020-04-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200404_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
